# Generated by Django 5.2.16 on 2026-09-07 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_aiproviderfeaturesetting_and_more'),
        ('database', '0220_alter_formview_mode'),
        ('integrations', '0033_coregotonodeservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalBaserowPasswordAppAuthProvider',
            fields=[
                ('appauthprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.appauthprovider')),
                ('password_field', models.ForeignKey(default=None, help_text='The field holding the hashed password of the user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='local_baserow_password_auth_providers', to='database.field')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.appauthprovider',),
        ),
        migrations.CreateModel(
            name='LocalBaserowUserSource',
            fields=[
                ('usersource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.usersource')),
                ('email_field', models.ForeignKey(default=None, help_text='The field holding the email address of the user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_source_email_fields', to='database.field')),
                ('name_field', models.ForeignKey(default=None, help_text='The field holding the name of the user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_source_name_fields', to='database.field')),
                ('role_field', models.ForeignKey(default=None, help_text='The field holding the role of the user. Without it every user of this source shares the same default role.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_source_role_fields', to='database.field')),
                ('table', models.ForeignKey(default=None, help_text='The Baserow table containing the users.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.table')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.usersource',),
        ),
    ]
